#!/bin/sh

# echo "What name for you prefer for your virtual environment?"

# read VEN_NAME

echo "Creating virtual environment"

python -m venv $VEN_NAME

source ./$VEN_NAME/bin/activate

pip install poetry

pip install -U pip setuptools

poetry install

